name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - feat/*
      - main
      - release/v[0-9]+.[0-9]+.[0-9]+

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changes:
              - 'app/**'
      - if: steps.changes.outputs.changes == 'true'
        uses: ./.github/workflows/lint-app.yml

  build:
    uses: ./.github/workflows/build.yml

  e2e:
    uses: ./.github/workflows/e2e.yml

  test:
    uses: ./.github/workflows/test.yml

  all-tests:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()
    steps:
      - run: sh -c ${{ needs.build.result == 'success' && needs.test.result == 'success' }}
